#include "audio_player.h"
#include "helix_mp3.h"
#include <string.h>
#include <stdint.h>
#include "mp3dec.h"

#define PCM_BUFFER_SAMPLES 1152   // Max samples per MP3 frame (mono)

static HMP3Decoder decoder;
static MP3FrameInfo frameInfo;
static FIL *current_file;

static uint8_t mp3_buf[AUDIO_BUFFER_SIZE];
static int16_t pcm_buf[PCM_BUFFER_SAMPLES];
static int mp3_buf_bytes = 0;
static int mp3_buf_index = 0;

// Double buffer for DMA
#define DMA_BUFFER_SIZE 2048  // samples
static int16_t dma_buffer[DMA_BUFFER_SIZE];
static volatile uint8_t dma_half = 0;

extern SAI_HandleTypeDef hsai_BlockA1;

void audio_init(void)
{
    decoder = MP3InitDecoder();
    HAL_SAI_MspInit(&hsai_BlockA1);  // Generated by CubeMX
    HAL_SAI_Init(&hsai_BlockA1);
}

// Start playback of a file
void audio_start(FIL *mp3_file)
{
    current_file = mp3_file;
    mp3_buf_bytes = 0;
    mp3_buf_index = 0;

    // Pre-fill DMA buffer
    audio_feed();
    HAL_SAI_Transmit_DMA(&hsai_BlockA1, (uint8_t*)dma_buffer, DMA_BUFFER_SIZE);
}

// Fill DMA buffer with PCM samples (call in callbacks)
void audio_feed(void)
{
    int samples_filled = 0;

    while (samples_filled < DMA_BUFFER_SIZE)
    {
        // Refill mp3 buffer if needed
        if (mp3_buf_index >= mp3_buf_bytes)
        {
            UINT br;
            f_read(current_file, mp3_buf, AUDIO_BUFFER_SIZE, &br);
            if (br == 0)
                break; // End of file

            mp3_buf_bytes = br;
            mp3_buf_index = 0;
        }

        uint8_t *p = &mp3_buf[mp3_buf_index];
        int bytes_left = mp3_buf_bytes - mp3_buf_index;

        int offset = MP3FindSyncWord(p, bytes_left);
        if (offset < 0) break;

        p += offset;
        bytes_left -= offset;

        int err = MP3Decode(decoder, &p, &bytes_left, pcm_buf, 0);
        if (err != 0)
        {
            mp3_buf_index += (p - &mp3_buf[mp3_buf_index]) + 1;
            continue;
        }

        MP3GetLastFrameInfo(decoder, &frameInfo);
        mp3_buf_index += (p - &mp3_buf[mp3_buf_index]);

        // Convert stereo to mono (take left channel)
        for (int i = 0; i < frameInfo.outputSamps/2; i++)
        {
            if (samples_filled < DMA_BUFFER_SIZE)
                dma_buffer[samples_filled++] = pcm_buf[i*2];
        }
    }

    // Fill remaining buffer with zeros if EOF
    while (samples_filled < DMA_BUFFER_SIZE)
    {
        dma_buffer[samples_filled++] = 0;
    }
}

// DMA callbacks (in main.c or stm32l4xx_it.c)
void HAL_SAI_TxHalfCpltCallback(SAI_HandleTypeDef *hsai)
{
    // Fill first half of buffer
    dma_half = 0;
    audio_feed();
}

void HAL_SAI_TxCpltCallback(SAI_HandleTypeDef *hsai)
{
    // Fill second half of buffer
    dma_half = 1;
    audio_feed();
}
